# numpy
##  1.ndarray对象
- ndarray可以进行矩阵操作

In [2]:
import numpy as np
l = np.arange(1,11).reshape([2,-1])
print(l)
# print(np.sin(l))
# print(np.exp(l))
print(np.mean(l))   #均值
print(np.median(l)) #中位数
print(np.ptp(l))    #极差
print(np.var(l))    #方差
print(np.std(l))    #标准差


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
5.5
5.5
9
8.25
2.8722813232690143


In [ ]:
# 切片
arr2d = np.arange(1,13).reshape(3,4)
print(arr2d[1:3,1:4])  #行切片 列切片
print(arr2d[0:2,:])    #行切片 所有列
print(arr2d[:,0:2])    #所有行 列切片
print(arr2d.T)         #转置

[[ 6  7  8]
 [10 11 12]]
[[1 2 3 4]
 [5 6 7 8]]
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
